### ISSUE TITLE
Invalid expiration time

### ISSUE THREAD

**Issue by palbee** [SecurityInnovation/PGPy#151]
It appears that the PGPKey.is_expired property incorrectly reports that the attached key is expired.
pgpdump indicates that the key does no expire until Fri Apr 28 05:26:22 PDT 2017.
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.11 (GNU/Linux)

mQENBE+dM24BCACxXURbx6PlW542wiwZR59RifON8Dkl3XkImLvrgJ2dgV+5jYo7
4DRAk0gNIlLsfrfVvL2k7qY+qBaMTavZKgTEIvtjRgL/fTxAEKndO8u49I9yZ7dc
juqOgTFOr+pq+TFk/2ZtILYBSnSJXJ5rmlS0eDptyRSRkqyDeCeZm1nUrXBud4GQ
oD+G57umYEtgKGSosrjQ2L66Ak31QL3izLu0NMciJb2tZQGdy4/ZdkyCLxLlm68X
THEjhaGMjykLKNLW3gAhTzLjSJTBF81nzwCBoj9Ov1RQgoMeyLQQGer/GyVn2119
VjL7Mv1VeNzbN0FUiJ9YEE5OKMqlwz7wxmEXABEBAAG0TlRlc3QgS2V5IChBcHRB
cHByb3ZhbCBUZXN0IFNpZ25pbmcga2V5KSA8dGVzdGluZytraW9za0BzZWN1cml0
eWlubm92YXRpb24uY29tPokBPgQTAQIAKAUCT50zbgIbAwUJCWYBgAYLCQgHAwIG
FQgCCQoLBBYCAwECHgECF4AACgkQglo3ewzq2mvbxAf/Tlv0W6mG/GaREl6D49cV
PwDQg9/yH0VpXB8qv1l0N2W1VsTF7iH3xe23Gi6PZzyxfcPUXAjdIz57pMqxH1SY
cze90pfDn/8c7VHVeRDCG17H8gt19PM+Xk6QvbJCV0aK1ECfwZNjDFmB+VnPqHCz
qNYFCeRP1X98Npzlrl5dz/la0Eel+ZIE3pGJ/pdkBeGAMKBvxKu1HenMVB88aKAe
ShlIDhSS/UoRCYX7Wu0VuhtqoYme9efFW1oqPXsD56bURe7IGwstfxTx04HfyMje
eUtHaI0aNPZwwkMKMljaNFXhV2uAnOL4iF2mjspZACHygiy1cNXLEPszzL377eme
XbkBDQRPnTNuAQgAuDktqcnZPMyAzhjy5QSj+ofvQe81NQvX0fVY04JME81HU7tP
gRRzmHZm6VVPhDxCj4YBxymtiTKoRnSE3peuMKqbudM8JCnGm6qsHuz01e4Z/r2B
8J44ZgRB1yUbaegN4fppVm7F+BdGGnFy/yXugkyizJq2VdFmiLNWRSQ4bqG59+XZ
5NDsP+c6Pf4Gx/CBTrSgGLuJEXDwXn+35CFhvdWp8AYF1JIpt7qpfJkiaqQCdbSx
CvS0WfAeA1TLg6+1rhDpPtkAjXiPL4dmdqCA167IlyGARTLHP0GlqayETDfe6snB
qqu1faM1liiiwdQ7lvjJst8P2X7XF6Sry8/RvQARAQABiQElBBgBAgAPBQJPnTNu
AhsMBQkJZgGAAAoJEIJaN3sM6tpr5AsH/22VHBPGgA+azZ0xCTe5e2e6I6BnWTdg
BcxddkF6O3AaCEaGR4jNS9VLMZCSGU4pTUVS+1tQlI7c01iyPlBEY31zoFyS6i4n
8uXkYGrhDu5Rxw5gWbOONaryi39+anqSD2HTxa8ALn6ktCHALCHqczytIjGXu6Ol
12ZF7d6EGxEIQ734PMCAPeYbH8iZZJ8Oi8zV7eOxbBw/A53jPF1hfrAraraTNUeV
vnyOhA3FHxxnJFe51zcuX3G68AGy77wFQCNQ1TluqlVsO7ZYLrMG0374hGGqTGRs
7z9Ep7wFb8bdztIt30fLddS0SjYAjaKaVT/+wfISwxVtBW9nCMg8t+U=
=psxH
-----END PGP PUBLIC KEY BLOCK-----

**Comment by Commod0re** [comment]
fixed in dev
