### ISSUE TITLE
ASCII Unarmor Issues

### ISSUE THREAD

**Issue by amrosado** [SecurityInnovation/PGPy#156]
It seems like the ASCII unarmor component within types could be improved.  I have an error importing keys generated using openpgp.js and it seems the primary problem originates from how bytes/strings are handled and the regular expressions used during the process of determining the object types and parsing the string.  Has anyone else had this issue?  I'm thinking of rewriting this component.

**Comment by Commod0re** [comment]
I grabbed openpgp.js and generated a basic keypair to try this out and it didn't fail for me with PGPy 0.4.0 on Python 3.5 when loading the key from a file.

I am not super familiar with node or openpgp.js, so after installing it via npm I followed their basic examples to generate a basic keypair like so:

```node.js
var openpgp = require('openpgp');
var fs = require('fs');

openpgp.initWorker({path: 'openpgp.worker.js'});

var options = {
    userIds: [{ name: "T.K. JS", email: "openpgp.js@email.com" }],
    numBits: 2048
};

openpgp.generateKey(options).then(function (key) {
    fs.writeFile("openpgp.js.sec.asc", key.privateKeyArmored);
    fs.writeFile("openpgp.js.pub.asc", key.publicKeyArmored);
});
```

Once that was done, I tried loading them into PGPy 0.4.0 on Python 3.5 like so:

```python
from pgpy import PGPKey

# loading the key by reading it and passing that data to PGPKey.from_blob worked as expected
with open('openpgp.js.sec.asc', 'r') as kf:
    data = kf.read()

priv, _ = PGPKey.from_blob(data)

# loading the key by loading it using PGPKey.from_file didn't raise an exception,
# but does spit out an unexpected warning:
#    /PGPy/pgpy/types.py:176: UserWarning: Warning: Orphaned packet detected! <LiteralData [tag 0x11] at 0x7f1a6877a668>
pub, _ = PGPKey.from_file('openpgp.js.pub.asc')
```

Does this match what you're seeing, or are you having a different issue?

**Comment by Commod0re** [comment]
Ah, I see. It looks like openpgp.js (or fs.writeFile maybe) adds carriage returns, and `Armorable.is_ascii` doesn't handle that because I missed it by not actually having any files with carriage returns in my unit test data!

It also looks like I didn't quite get the regex correctly handling the existence of carriage returns, either - although newlines come after line end anchors, carriage returns do not.

**Comment by amrosado** [comment]
`I` think I remember getting this order before, but the key that was loaded was distorted and didn't have the correct information loaded.  I never tried loading the key from a file I was trying to transmit the public key information over HTTP.  When interpreting the bytes related to the information or a string, basically I thought the error was related to encoding issue.

I actually changed the way regular expressions were done on the key and by modifying them I was able to get the information from the key correctly determined.  It was falling to determine remove the ASCII armor from a string because it failed to interpret the ASCII armor encoded within the request.  Additionally, I changed the regular expressions for grouping the information within types.py.

`m = re.match(r"""# This capture group is optional because it will only be present in signed cleartext messages
                         (^-{5}BEGIN\ PGP\ SIGNED\ MESSAGE-{5}(?:\r?\n)
                          (Hash:\ (?P<hashes>[A-Za-z0-9\-,]+)(?:\r?\n){2})?
                          (?P<cleartext>(.*\n)+)(?:\r?\n)
                         )?
                         # armor header line; capture the variable part of the magic text
                         ^-{5}BEGIN\ PGP\ (?P<magic>[A-Z0-9 ,]+)-{5}(?:\r?\n)
                         # try to capture all the headers into one capture group
                         # if this doesn't match, m['headers'] will be None
                         ((?P<headers>(^.+:\ .+$(?:\r?\n))+))?(?:\r?\n)?
                         # capture all lines of the body, up to 76 characters long,
                         # including the newline, and the pad character(s)
                         (?P<body>([A-Za-z0-9+/]{1,75}={,2}(?:\r?\n))+)
                         # capture the armored CRC24 value
                         ^=(?P<crc>[A-Za-z0-9+/]{4})(?:\r?\n)
                         # finally, capture the armor tail line, which must match the armor header line
                         ^-{5}END\ PGP\ (?P=magic)-{5}(?:\r?\n)?
                         """,
                     text, flags=re.MULTILINE | re.VERBOSE)`

By removing the $ anchor and using re.search instead of re.match it seems to work.

**Comment by amrosado** [comment]
Also, I apologize if I do a poor job of contributing to documenting my issue, etc.  I'm not really well versed in the discussion of the issues on publicly available repositories.  I am more used to working on low level personal projects.

**Comment by Commod0re** [comment]
No worries, I just wanted to make sure I was actually looking at the same issue you reported :)

I've made the same change suggested to the regex and fixed Armorable.is_ascii so that should all be good in the development branch now.

For anyone else who comes across this and doesn't want to modify their copy of PGPy before the next release, the simplest workaround is to just remove the carriage returns from the armored blob beforee trying to load it with PGPy.

Thanks so much for reporting this issue, by the way!
