### ISSUE TITLE
Protect Changes Key to Protect With Password, but Unlock Doesn't Work

### ISSUE THREAD

**Issue by amrosado** [SecurityInnovation/PGPy#159]
I can't seem to get my key to get unlocked after protecting it with a passphrase.  The unlock method doesn't even seem to get evaluated within the PGPKey method and I don't really know why.

**Comment by Commod0re** [comment]
How are you trying to unlock the key? That method is a context manager, so it won't have any useful effect by just calling it

e.g.

```python
In [22]: k.is_protected
Out[22]: True

In [23]: k.is_unlocked
Out[23]: False

In [24]: k.unlock('asdf')
Out[24]: <contextlib._GeneratorContextManager at 0x7f50d6b9e2e8>

In [25]: with k.unlock('asdf') as uk:
   ....:     print(uk.is_unlocked)
   ....:
True

```

**Comment by amrosado** [comment]
I see now.  I was able to get it to successfully function with your help.  Still having trouble with parsing the message returned from th server and decrypting it with the private key though.
