### ISSUE TITLE
NotImplementedError <class 'pgpy.packet.types.Opaque'> when decrypting string

### ISSUE THREAD

**Issue by seddonym** [SecurityInnovation/PGPy#160]
I have a string containing an encrypted PGP message.  I'm trying to decrypt it using my private key, but I get this exception:

```
encrypted_contents = """-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.6.1.0

hQEMAzryfcwJ5IDHAQgAjpVqmIjBXdTGHIjRUSrvfXMIV4IOHlERan9AXbhxdaBo
9p23qVV+Jgah7rVBWJWJ1oeLFy0C1XaP56Xc4oZIWHl9mnd2cNvg4q859ZYvldFA
apB4icAvLqBFnRGM8UzdxOjI1M3jgzfvue3dLe72Hkf8eOYxWEDd9XAgySrEEXSn
IhZnFFkeoCr13jSGex0wEQcsMC00YHalPSCs6Rdz0Pke6o7T1vKE7i7uiBvzJqqP
Rx6C1O3cwNAm2t+q5t0YIBvjQ8Qb19Nq12+1mFTtww6YtxikcNR9vj0hnBMpw9L3
J1NWAVrEBClNFjVyz9Xw3dqTfMuEaG+GeGCc6m+7lMnDrQHR5tf4mjtS3rpiAUqw
mzyBHM/MSfLQGJ5x9Okl94KeRpgvnrJbGewL6sjTcJ6J8xmJEntNbk1Wqis5kv6N
VtIaZWjqokejaHQtvAfODerGD8a9+iz3X/G2pKQekF3bM3gcoxdg0Ac+yitjuEV/
Kdo5XBm0xTL0CuQqUKM4fEXADcwaaM5vQ99g0yrs3SEhgx37HVImaMwYhEzpgVTz
18fZHG2E+TOBvEvAaY3TbTV3klEEvlaT7e+MTLGMJTbGGCTbwUnsyI3gX+Aj1Wc0
nE4Q7IMJ+BilCR+SyuAqsjm8IpgHmz985iAawp2YfKmy3M6IMLqwMyb05rHMA3H7
iLA4ISvycXwEB0ij7S3YAdrisUNzhnFmja955Yru9A7m6CUWc64K3uO6HxOS4JrS
n3i2gDSyy5723QLZcs1TxCPfLxFOhGa9Dc0/x+jNSg5Dr3kM9DmM8kxaKh3MZK1q
2esQpET7kFBPCkeBcBGff/L0XvAdLeR68cCFBEzJZex75CkuFyJWEcA2BoycUn/L
2/xlMOhPMsAnKMjc09QxbSYLwchdrAkhth1nDvUlU6T97cNApjExHC3L1piXfCne
amIVJyL4sesAs7rzNFKEa05mPPPO3PtlXppCvNsYE1SalZWPKvjUIdS6x5jn6t2/
y4llQyap0k+Oi37WqeP5auic/sjbEbgncxzyjFogc7Zp9JyuPpwfuGCpCvpt5bS8
88cjZbWB44wK0vLNNNidHErxbS2kUTbse8gaQskK4KGq/mtWl1E81gKoe7PI/XP/
wKbprD6A84HF+7oTRDM5h/OGM457nVWpzU9b2pZx1v/pUoRHcJch9M39TSOFPGxP
Emlf4ajKUe4hcay06u/8ksA+j6132ItrWU8TqO/K6MNfabihQE9Ps7MHwTn1katt
yIdjKE0si4Y0hBTWA/Z/jWTn26sIfIrNd+3Xwnlh9PjrbBEsVzTnjtO8LiAVFEp+
8D+jthkj2bQ813tSGd6ycm+xmwa9q+T0xjB7uIchDZ1W0u0/R/jpjG7VvY/YA7MB
N8V1JV1b3s5ze5PMFSeRMyrBaqe6Y7fPzNUNbSgE1tKLFiQCCsmhnBWnBzqahnDJ
mHqweX4WYMOED35tJMRzK4ixJtmuZ9ezDUjnil/TgIbtx+NfJnte1FHdRB/DvPAK
dG2h799jR7Jct9dVqSblRaPMGaStsruIviC8b/HaNOxad+iJTj+nv2Nng1nuYdqR
aPOw+jphJzM8tmsw1rLXkZugdLb0Rx/xaJpXjfSsyVgYmZQeVkpGwPgaXgTdr363
jfNXwJYi3O881qo5MabOAXNnrAKfq2lfhpvSt1sW4S/wFoUAqPGaj/kUP5u+eX5z
xFruKZOaLIR56qXdoRtRRIQLxiSGGyiP3cSI02l+I2GmGTJ3DfgfJ2EVj933dSGs
Kh36bFnO1JQ0xPV4Q1/r/wfRVVwr1qK0GO/HmH6+zltru36ZaVs8IL2/kh4mjBBf
MxHvUdYk5wqhrXqat6YZ
=u1YX
-----END PGP MESSAGE-----"""
import pgpy
pgp_message  = pgpy.PGPMessage.from_blob(encrypted_contents)
private_key = pgpy.PGPKey.from_file('/path/to/private.asc')[0]
private_key.decrypt(pgp_message) 
```

Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pgpy/pgp.py", line 2187, in decrypt
    decmsg.parse(message.message.decrypt(key, alg))
  File "pgpy/pgp.py", line 1084, in parse
    self |= Packet(data)
  File "pgpy/pgp.py", line 874, in __or__
    raise NotImplementedError(str(type(other)))
NotImplementedError: <class 'pgpy.packet.types.Opaque'>
```

I've tried this on both Python 2.7 and Python 3.4.

**Comment by seddonym** [comment]
Apologies - I just saw this issue, which seems related: https://github.com/SecurityInnovation/PGPy/issues/158, but is closed.

Here are the outputs you ask from the other poster, doesn't seem like it's suffering from the same issue:

```
$ pgpdump message.txt 
Old: Public-Key Encrypted Session Key Packet(tag 1)(268 bytes)
	New version(3)
	Key ID - 0x3AF27DCC09E480C7
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA m^e mod n(2048 bits) - ...
		-> m = sym alg(1 byte) + checksum(2 bytes) + PKCS-1 block type 02
New: Symmetrically Encrypted Data Packet(tag 9)(1133 bytes)
	Encrypted data [sym alg is specified in pub-key encrypted session key]

$ gpg --list-packets message.txt 
:pubkey enc packet: version 3, algo 1, keyid 3AF27DCC09E480C7
	data: [2048 bits]
:encrypted data packet:
	length: 1133
gpg: encrypted with 2048-bit RSA key, ID 09E480C7, created 2016-06-15
      "XXXX XXX <x@xxxxxx.xxx>"
:compressed packet: algo=1
:literal data packet:
	mode t (74), created 1465974278, name="text.txt",
	raw data: 7090 bytes
gpg: WARNING: message was not integrity protected
```

Let me know if you think it's a bug, or if it's me using the library incorrectly (in which case perhaps the documentation could be tweaked).

Thanks!

**Comment by Commod0re** [comment]
This looks like a slightly different issue, but it is similar. As I noted in #158, OpaquePacket is dispatched as a last resort when parsing packets if another registered packet class matching the parsed header is not present.

Most of the time this means one of the following things is true:
 - A packet that was parsed is not (yet) implemented in PGPy
 - A parsing bug caused PGPy to get misaligned on the data
 - A packet that was parsed is malformed somehow

In your case, the encrypted packet was parsed correctly, but PGPy did not understand something from the decrypted data. Looking at the output you've provided, I don't see anything that should obviously fail to parse, so I will operate under the assumption that this is probably a parsing bug while I try to reproduce the issue myself.

**Comment by Commod0re** [comment]
After reproducing this issue myself, I have determined that this is indeed a bug relating to decrypting Symetrically Encrypted Data packets.

You can immediately work around this issue by having your BCPG code encrypt messages with integrity protection enabled (e.g. pass `true` for the `withIntegrityPacket` argument when instantiating `PgpEncryptedDataGenerator`) . I'd recommend using that mode going forward anyway, but it does also avoid this issue.

**Comment by Commod0re** [comment]
That assumes you have control over that particular codebase, anyway. Otherwise, it's not a very useful workaround for you!

**Comment by seddonym** [comment]
Thanks for your quick response!  I generated the message using a different piece of encryption software and I was able to decrypt it, so the workaround works for me for now.

**Comment by SirCmpwn** [comment]
I get the same problem with this PGP message:

```
-----BEGIN PGP MESSAGE-----

hQEMAwDxEZj45VMLAQgAjGBt6COiJcbfliqrni+bjH/Zm5g4K7fp1XP37H7U4mxL
p6/yJyk142aQ7CxPQTZtln7NWTozyw8dZqkldrFhdmm9m0soC8veDufYdrVBW6LT
w5xJYv6uzHxnqTge7HWZLoMd7kbh1fqw43YQgYe4HeDgs9eU9vzV2qlD95ru5v2O
1R9RmRrmLLYE75YgKtWqud9XmR1h7ePk75DeAptrEe4U8eYw+Z5I3iNIjyLSMP8d
M8B0SYhWNKg5sszOcvtMNry97HoExkRP2cGjNTQBkZn9ZlOvqlktqRpU+o8uvRv0
fRglqPr9dgqQQujavyluiNCfmzPkVnGAc+ziX5cM+NLqAWy6RjnU/CGm8tjRKIDu
luZMQ2e3BMmqdatQg3Ft2QsJmjCM/hJTR+P07gp75cIUWu+ZfOgf96JV+XjGfYXR
qf8jhfscm3CTWyMfkcOOfymSgBVivuRa/BsHT+wi85VPesPXYD9KX9lthchlj21G
HHBNbhIVBKOpDalUdLoYMBR/lQ5U1I/e4qnlmhyYjdGN20QaoNFkMkUjoTCUxf5O
7PzA3zc2hhexNqJMdJymVedTiXvkKbGw5ZMj3KXtDZcGhFt8KcJ+rFtPS8PCp/07
aQ3Qh12Wp756xtwI4/OTHZ6COlKT29QAqUARfFXbtPIZwGgYB+UoqPuZUw4wP1co
P9lJKGCNfq5fiZnqbr9l+lgWib4oGEmdf44pkREQexxy93BHUzWQAaaxcbiFBFoq
dFR0pvdXjG4RqYVALxU+wn7UmvVcDiaw8VVIRZV1mUS3f0h5C+UUjVZWBLd+yBhd
QQEG7ZfjwSYva+O664PTyF9Brlh50rlo79Ewi2Sp50zQ5IMt5Ys7oX8VWGCdn+0P
0gnDYs1dr+vI++DNepXS2MLgw/cnDFjdE918pd2lXgcsX8le9vv71KqDiPIElkWa
KHfKF7bTKX8Y4OjeejBXez4cgQMJDzc25FpwiMSXHfTP/er4zsGPqv7CiD+iVxyT
tKtc2NL8AWNM1nPqifS5n6ADRX6kQr+oZDx5vwHy+Wy1R5CTm8Rx22jp3msE78pU
sgdTnYhni+fcG3QZpYhLT3Xwl3qZzQy8zHpl6SXRz299dUFh4d5Ypy1gSyRL4jjD
UR972O2yRjwbjHeQ1CrvbOPhWTm8d4pHuj++3M4589vKImJXn9d+wSbU+sMSd3nN
LGcKKjdeEtV6WQBa96yzI7+rnEfGPzZ/Mp7C4uOP7s4feGOadc1m+8+dWRaQhewB
NZ7IQLA6HWjfKg8BVJGjIvSSIZlCgOR+gzsTCYf4b/6ZGsxaJ9X5ii2JMXPb1z8z
1tJA0HCEThzZ8LXD0AEMrkcEKKn6a5iUboiBo4WKXyrFfgkZHWW16Sn/TAZD7dDy
WodpFBQPzQs8g9jh2UuatyBdccSQQyxUd75+7gargzrNQvWhwPVJA7jcx1kHya6B
qPk/ds0szwye4b5hlRpugxqiUlNYr7iCe4ebPacdvsCHDAmIrNEsahQribOvfVu5
2TZtZU24VvbLzGJRzQOmcKTGetXzGx+15YTWr8DaPtVmdIlM5S48hohYvDSod0Xf
fOxsq4TV5FCcDGCTz62ItTN7e7CorJtZgj+rseyzZgPQ0Hqz0HECZANOTUgDPVE8
OY9dR+VqBbN9AJfC31lZUfiZgpbtN9cPBgXQDyV2zQ7HFYebMb/8Lz9AthToEe9j
T+le8GtMriRt2kazAEkFSudt2tzbYkg9Bara5Ihpw/juXH4nxAG5c2uXr0jbMWAL
IiPm6hblizj2VQKR1TMN5y1ssHdDUftkjSz3hamvmJIcCbtOzQhWx/Y68LB9r92/
nuMpxYoL+Bs5zi6pyGCfMAoEGpB/eNBUJDPdmvyvdLDrlAz7wTDkrVbmd0hpTVlh
qkg2EooreAs7JuPsNAiBTj11MR/DkEzn5ki7E69zUKwrs09O4wkGGXpuCpSNDbxo
HjNg1983cVfNyqnE4zk47TU+L109GSVLVeH7BWd90KHQuO7d5eS7ki+VEP9gzGC3
3l045wtwz5dLKUF/fNgv3Oz1yIlq4B/AUZccNRVvP4QtyKg1iPn3C+InsTUE63Td
Si0F5iRJW4CEtxDI71/9zW2lMtDFBk3m0anGRPKueRK3iupkn4iZ18EFrAwzE/Bn
0zzGm8sribo9+WcYWx0W/x/ciq8rHC/GKIodd+npOosRYw4iI9k4ZhNhxVxO9ILK
DZfZ0VbwI4CKAqhJcr2HxFSbuAeBzp3A3lkNr2FylH9aEPBXOJ7Qa0DlOSZRtUE+
TE0kgklFt7lTKVctOLDNWo4nGx6nSo2aekzRCTs/UitYwLLf1VMr5BcQh5+AblM3
qiVGMRSsUDmPRR7/rK7bK3UL9RkWJ2lnp0CZa/W0z+C6+Z7KD/x8pAwQzkcmUhj1
U2wf5s6HkFAx7ZDEh2FBJLj+Gnjbej1Zj2Aa70ED6TkCVvUK53/o8ebM1aye1uxH
T+WzHxus9tCyODKgTWmIhyFnRhqBLcVn23Azvxg/N7+7iye+ZCosFQGPaZQozhEu
qJV7G/Sbm4JUQnsaVL2OiFoX4Hha9SKiM3ZUC+at2mqBrnoAlNqkXjO0y6GrI6MZ
wg==
=emPd
-----END PGP MESSAGE-----
```

**Comment by SirCmpwn** [comment]
This was just created with `gpg --encrypt --armor`

**Comment by Commod0re** [comment]
That appears to be a different issue. Creating messages with gpg through a pipe tends to create packets with partial length headers which are not yet supported by PGPy (see #95):

```
$ pgpdump SirCmpwn.asc
Old: Public-Key Encrypted Session Key Packet(tag 1)(268 bytes)
	New version(3)
	Key ID - 0x00F11198F8E5530B
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA m^e mod n(2048 bits) - ...
		-> m = sym alg(1 byte) + checksum(2 bytes) + PKCS-1 block type 02
New: Symmetrically Encrypted and MDC Packet(tag 18)(1024 bytes) partial start
	Ver 1
	Encrypted data [sym alg is specified in pub-key encrypted session key]
		(plain text + MDC SHA1(20 bytes))
New: 	(512 bytes) partial continue
New: 	(158 bytes) partial end
```

**Comment by SirCmpwn** [comment]
Actually I just composed that message by typing it into stdin, which is basically the same thing. But it's also how I encrypt probably 30% of my PGP messages.

**Comment by Commod0re** [comment]
Ah yes, it does do it in that case as well, if the input message is not short. It's not ideal, but [I did find a workaround](https://github.com/SecurityInnovation/PGPy/issues/161#issuecomment-226626409) by specifying the `--set-filesize ##` flag for gpg, until support for partial packet length headers is implemented

**Comment by Commod0re** [comment]
Ah, that makes sense. I will do my best to make time to implement that as soon as I can, then

**Comment by SirCmpwn** [comment]
Cheers, thanks

**Comment by gdchamal** [comment]
I encounter same problem regarding a packet type 18.

When trying to debug a bit this situation, I see that packet to be parsed have a strange first value, that will be used as packet version.

With use of the PGP MESSAGE in this thread I found that:

```
ipdb> 
######## <class 'pgpy.packet.types.Packet'> 18 <class 'pgpy.packet.packets.IntegrityProtectedSKEData'>
> /home/mric/dev/caliopen/go/src/github.com/CaliOpen/Caliopen/ext/PGPy/pgpy/packet/types.py(143)parse()
    142             ipdb.set_trace()
--> 143             self.version = packet[0]
    144             del packet[0]

ipdb> packet
bytearray(b'\xea\x01l\xbaF9\xd4\xfc!\xa6\xf2\xd8\xd1(\x80\xee\x96\....)

```
packet[0] = 234
packet[1] = 1

Sound like an extra byte make parsing failed and fallback on an Opaque packet type in MetaDispatchable._registry

I reproduce same one byte shift with another PGP Message I've got trouble with (and make me find this issue).

**Comment by SirCmpwn** [comment]
Bump. Got time to look into this?

**Comment by gdchamal** [comment]
Using the latest release of pgpy (0.4.3) I can't reproduce this error. I think this is related to https://github.com/SecurityInnovation/PGPy/pull/208 and may this issue can be close

**Comment by kmbeyond** [comment]
Hi there, I am seeing this same error with 0.6.0 for a pgp encrypted data file using assymmetric key.

Is there a workaround or solution in Python to be used in automated job?

This is my error for command:
>>> pgpy.PGPMessage.from_file( '/path/data_file.csv.pgp' )

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/python/venv2/lib/python3.9/site-packages/pgpy/types.py", line 195, in from_blob
    po = obj.parse(bytearray(blob, 'latin-1'))
  File "/xxx/python/venv2/lib/python3.9/site-packages/pgpy/pgp.py", line 1293, in parse
    self |= Packet(data)
  File "/xxx/python/venv2/lib/python3.9/site-packages/pgpy/pgp.py", line 1080, in __or__
    raise NotImplementedError(str(type(other)))
NotImplementedError: <class 'pgpy.packet.types.Opaque'>
