### ISSUE TITLE
Document where to interact with community (if anywhere)

### ISSUE THREAD

**Issue by BjarniRunar** [SecurityInnovation/PGPy#164]
Hello!

PGPy looks very interesting, thank you for making this. I was looking for a place to interact with the developers and/or user-community (IRC, a mailing list, Twitter) in a less formal way than by filing issues here. Is there such a venue? If there is, it would be great if it were documented in the README so people can find it. If not, maybe there should be?

Thanks!

**Comment by Commod0re** [comment]
There isn't currently, but that does sound like it could be a useful thing indeed! I'm open to suggestions (other than Twitter), if you (or anyone else) have any preferences

**Comment by BjarniRunar** [comment]
Happy holidays!

I am old-fashioned and I am quite fond of both mailing lists and IRC channels.

I've noticed that quite a few open source projects seem to be using Matrix's [Riot messenger](https://riot.im/) to bridge the old universe of IRC with modern expectations of a web-based slack-like UI for live chat. I haven't tried it myself yet but I've been meaning to for a while. :-)

**Comment by anarcat** [comment]
i see a lot of communities use Gitter for that purpose. i used to avoid recommending it because it was  proprietary software, but now that it's been bought by Gitlab, it will be open-sourced. it is trivial to create a room for a GitHub project there and bridges through IRC.

basically, i see it as a fancy web interface for IRC. :)

**Comment by Commod0re** [comment]
That sounds pretty cool, I'll take a look at these things. I've always liked the idea of IRC, but I've not always been able to get in the habit of remembering to connect on a regular basis. Maybe it's time to fix that 8)

I guess I'll start with registering a channel on freenode unless anyone has a strong preference for another network. I'll try to make some time to look further into at least Matrix and Gitter after that. Thanks for the input so far, everyone! It's been really cool to see people take this much interest in this project!

**Comment by Commod0re** [comment]
``#pgpy``is now registered on freenode, and added to the README

**Comment by BjarniRunar** [comment]
Cool!

It took me a few tries to find the README update though, it came as a surprise to me that release/0.4.1 is where the updates are happening, and there was no change on master.

I guess another suggestion would be to document in the master README which branches people should be looking at (because that's where people end up by default when browsing github)? But that's a separate issue, I think this one is resolved - thank you! ;-)

**Comment by Commod0re** [comment]
That will be fixed shortly. release/0.4.1 is just a temporary branch for staging before I officially push the release 8)

**Comment by Commod0re** [comment]
I will also add a point about the branches to the README - good suggestion!
