### ISSUE TITLE
Error importing pgpy generated keys with gnupg

### ISSUE THREAD

**Issue by juga0** [SecurityInnovation/PGPy#168]
when creating a new keypair with pgpy v0.4 (only with name attribute, not email, though this doesn't seem to matter), then export private and public keys to files, there are errors importing them with gnupg v1.1.18 into a keyring.

Here some cases tested:

- key generated with passphrase
 - key generated with subkey
     - import exported private key
         works
     - import exported public key
         `gpg: [don't know]: invalid packet (ctb=53)
          gpg: read_block: read error: Invalid packet
          gpg: import from '/tmp/F96AD179_wIyaJd.asc' failed: Invalid keyring`
          subkey is not imported
 - key generated without subkey
     - import exported private key
         works
     - import exported public key
         works

- key generated without passhrase
 - key generated with subkey
     - import exported private key
         `error sending to agent: Checksum error
          gpg: error building skey array: Checksum error`
     - import exported public key
         does not import subkey

 - key generated without subkey
     - import exported private key
         `error sending to agent: Checksum error`
     - import exported public key
         works

**Comment by juga0** [comment]
s/ with with/ with

**Comment by Commod0re** [comment]
Hey, thanks for submitting this bug report! I *think* I may have actually come across the same bug a few weeks ago, while updating the unit test suite. I'm trying to verify if that is the case, but I need just a little more information if it's not too much trouble. Can you provide the parameters (algorithm(s), key size, preferences specified when adding the UID) used when generating these keys where you found this issue?

**Comment by juga0** [comment]
Sure, no problem. Thanks for the fast answer.

Here part of the code:
```
    key = PGPKey.new(PubKeyAlgorithm.RSAEncryptOrSigny, 2048)
    uid = PGPUID.new(uid)
    key.add_uid(uid,
                usage={KeyFlags.Sign},
                hashes=[HashAlgorithm.SHA512, HashAlgorithm.SHA256],
                ciphers=[SymmetricKeyAlgorithm.AES256,
                         SymmetricKeyAlgorithm.AES192,
                         SymmetricKeyAlgorithm.AES128],
                compression=[CompressionAlgorithm.ZLIB,
                             CompressionAlgorithm.BZ2,
                             CompressionAlgorithm.ZIP,
                             CompressionAlgorithm.Uncompressed])
    if add_subkey is True:
        subkey = PGPKey.new(PubKeyAlgorithm.RSAEncryptOrSigny, 2048)
        key.add_subkey(subkey, usage={KeyFlags.EncryptCommunications,
                                      KeyFlags.EncryptStorage})
    if protected is True:
        passphrase = getpass.getpass()
        key.protect(passphrase, SymmetricKeyAlgorithm.AES256,
                    HashAlgorithm.SHA256)
```

**Comment by juga0** [comment]
Ah, and to export to files, `str(key)` and `str(key.pubkey)`

**Comment by juga0** [comment]
ah... and s/gnupg v1.1.18 /v2.1.18

**Comment by Commod0re** [comment]
After checking this, it looks like I don't quite have it fixed like I was hoping (importing the public key sans subkey works, but the public subkey got mangled somehow), but I will track this down this weekend and release v0.4.1 with this issue fixed hopefully shortly thereafter

**Comment by juga0** [comment]
Thanks a lot!

**Comment by Commod0re** [comment]
Fixed in dev, I expect to have time to finish up the 0.4.1 release sometime this weekend :)

**Comment by juga0** [comment]
I just checked with https://github.com/SecurityInnovation/PGPy.git@2514c3908d62ec6c82fcd99adf4738849667d540 and importing a private key generated with subkey and not protected still fails with gnupg.

**Comment by juga0** [comment]
.... with the error `Checksum error`.

**Comment by Commod0re** [comment]
That doesn't repro for me :/

```shell
 % gpg --batch --import key.subkey.protected.asc
gpg: key 6E7578BA6ABF6BB0: public key "Key (Key with subkey protected)" imported
gpg: key 6E7578BA6ABF6BB0: secret key imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
```

**Comment by meskio** [comment]
I'm getting the same `Checksum error` with the develop branch:
```
$ cat gen.py 
import pgpy
from pgpy.constants import PubKeyAlgorithm, KeyFlags, HashAlgorithm, SymmetricKeyAlgorithm, CompressionAlgorithm

# we can start by generating a primary key. For this example, we'll use RSA, but it could be DSA or ECDSA as well
key = pgpy.PGPKey.new(PubKeyAlgorithm.RSAEncryptOrSign, 4096)

# we now have some key material, but our new key doesn't have a user ID yet, and therefore is not yet usable!
uid = pgpy.PGPUID.new('Abraham Lincoln', comment='Honest Abe', email='abraham.lincoln@whitehouse.gov')

# now we must add the new user id to the key. We'll need to specify all of our preferences at this point
# because PGPy doesn't have any built-in key preference defaults at this time
# this example is similar to GnuPG 2.1.x defaults, with no expiration or preferred keyserver
key.add_uid(uid, usage={KeyFlags.Sign, KeyFlags.EncryptCommunications, KeyFlags.EncryptStorage},
            hashes=[HashAlgorithm.SHA256, HashAlgorithm.SHA384, HashAlgorithm.SHA512, HashAlgorithm.SHA224],
            ciphers=[SymmetricKeyAlgorithm.AES256, SymmetricKeyAlgorithm.AES192, SymmetricKeyAlgorithm.AES128],
            compression=[CompressionAlgorithm.ZLIB, CompressionAlgorithm.BZ2, CompressionAlgorithm.ZIP, CompressionAlgorithm.Uncompressed])

print str(key)
$ python gen.py| gpg --import
WARNING:vext:Could not add extra path: /usr/share/sip
gpg: key 9A91075A2E1DE413: public key "Abraham Lincoln (Honest Abe) <abraham.lincoln@whitehouse.gov>" imported
gpg: key 9A91075A2E1DE413/9A91075A2E1DE413: error sending to agent: Checksum error
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
```

**Comment by Commod0re** [comment]
So, that issue has to do with a change to gpg-agent in [GnuPG >= 2.1.9](https://lists.gnupg.org/pipermail/gnupg-users/2015-November/054730.html) where it won't import secret keys without passphrases without the `--batch` switch:

```shell
% python gen.py| gpg --import
gpg: key 34FC858F4858F8A0: public key "Abraham Lincoln (Honest Abe) <abraham.lincoln@whitehouse.gov>" imported
gpg: key 34FC858F4858F8A0/34FC858F4858F8A0: error sending to agent: Checksum error
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
```

```shell
% python gen.py| gpg --batch --import                                                        :(
gpg: key 63A6FD08F17F6125: public key "Abraham Lincoln (Honest Abe) <abraham.lincoln@whitehouse.gov>" imported
gpg: key 63A6FD08F17F6125: secret key imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
```

It's not a very helpful error message, unfortunately

**Comment by meskio** [comment]
Interesting, you are right, if I add the `--batch` switch it works.

I guess then it's not a PGPy issue and we can close it here.

**Comment by juga0** [comment]
I also didn't know we should use `--batch` there.

Thanks a lot Commod0re!

**Comment by Commod0re** [comment]
No problem, I came across that situation a couple of weeks ago while testing some stuff. I'm happy to be able to pass it along :)
