### ISSUE TITLE
debian packaging

### ISSUE THREAD

**Issue by dkg** [SecurityInnovation/PGPy#170]
Hi Michael!

I've put a debian branch at https://github.com/dkg/PGPy -- feel free to review it and pull it in and publish the packaging on your own debian branch if you like (i don't know how to make a github pull request to a non-existent branch).

I just uploaded the head of it to debian, which should put it in the NEW queue.  Given that we're in a freeze, it'll probably take a while to get out of the NEW queue, but i figure it's better to go ahead and start the process.  We can always tweak and improve the packaging as we go.

Let me know if you have any questions!

**Comment by dkg** [comment]
Here's the NEW queue, btw, if you want to track the progress: https://ftp-master.debian.org/new.html

**Comment by varac** [comment]
Hej, I'm looking for the debian package but can't find it.
[Pgpy Documentation](http://pythonhosted.org/PGPy/) sais:

```
PGPy is now in Debian Sid, and can be installed simply:
$ sudo apt install python3-pgpy
```

But the [link to the pgpy sid package](https://packages.debian.org/sid/python3-pgpy) shows no package, neither do a `rmadison python3-pgpy`.
What's up ?

**Comment by Commod0re** [comment]
So, that link did previously work, but there are a couple of bugs that surfaced in the unit test suite that have prevented some of their builds from succeeding. I guess the page for the package disappeared in the meantime.

Once #171 and #173 are resolved and the updated code is in @dkg's hands, it should (hopefully) resurface

**Comment by dkg** [comment]
anything i can do to help get these resolved?  i'd like to get this package back into debian!
