### ISSUE TITLE
Investigate test suite heisenbug

### ISSUE THREAD

**Issue by Commod0re** [SecurityInnovation/PGPy#171]
Very occasionally the gpg_print test fixture fails to return data even though it should have, causing automated builds to fail. I'm not sure if this is a timing error or what, but it needs to be fixed

**Comment by Commod0re** [comment]
[This](https://buildd.debian.org/status/fetch.php?pkg=python-pgpy&arch=all&ver=0.4.1-2&stamp=1492644100&raw=0) build log shows an instance of the bug. The relevant bit (this one is in test_decrypt_message):

```
            with gpg_import(os.path.realpath(sf)) as kf:
>               assert gpg_print(emsgf.name) == dmsg.message
                assert '' == 'This message will have been encrypted'
                  + This message will have been encrypted
```

**Comment by dkg** [comment]
This seems to be happening still with 0.4.2 :(

https://buildd.debian.org/status/fetch.php?pkg=python-pgpy&arch=all&ver=0.4.2-2&stamp=1502732722&raw=0

**Comment by Commod0re** [comment]
Something about that environment is different enough from mine (and from travis-ci) that gpg_print isn't working right over there for some reason. I'm trying to figure out how to reproduce the conditions that are causing it.

**Comment by Commod0re** [comment]
I have removed the gpg_* wrapper functions in tests/conftest.py and am using the gpg package for the tests that check against gpg, as I see that python-gpg and python3-gpg 1.8.0 are in sid already. As soon as the travis run passes, I'll release this as 0.4.3 and cross my fingers that 

It is off to a good start, at least: this method actually discovered that #172 was not fully fixed (one line went missing or never existed, I'm not too sure), so 0.4.3 will include that as well.

**Comment by Commod0re** [comment]
@dkg: I believe this issue should disappear with v0.4.3, which I have just released.
These two build dependencies need to be added to support the test suite: python-gpg and python3-gpg
