### ISSUE TITLE
decryption error NotImplementedError: <class 'pgpy.packet.types.Opaque'>

### ISSUE THREAD

**Issue by meskio** [SecurityInnovation/PGPy#174]
I'm getting the following traceback trying to decrypt a message:
```
Traceback (most recent call last):
  File "test.py", line 203, in <module>
    txt = pgpy_decrypt(pgpmsg)
  File "test.py", line 196, in pgpy_decrypt
    message = pgpy.PGPMessage.from_blob(enc_data)
  File "/home/user/dev/PGPy/pgpy/types.py", line 189, in from_blob
    po = obj.parse(bytearray(blob))
  File "/home/user/dev/PGPy/pgpy/pgp.py", line 1118, in parse
    self |= Packet(data)
  File "/home/user/dev/PGPy/pgpy/pgp.py", line 908, in __or__
    raise NotImplementedError(str(type(other)))
NotImplementedError: <class 'pgpy.packet.types.Opaque'>
```

This can be reproduced with:
https://gist.github.com/meskio/28bd52a7f723d019095ab1e9042d75be

The PGP message was created with alot, an email client that uses GPGME. I've seeing the same issue with emails created by mutt. But I've being unable to forge one of this messages by hand.

**Comment by meskio** [comment]
I forgot to mention, the key was generated from the lattest `master` of PGPy and gnupg seems to decrypt it correctly.

**Comment by meskio** [comment]
Adding some prints it looks like the Opaque packet has a tag `PacketTag.SymmetricallyEncryptedIntegrityProtectedData` (https://tools.ietf.org/html/rfc4880#section-5.13).

**Comment by meskio** [comment]
It looks like duplicated with #160, we'll need partial packet support (#95).

**Comment by Commod0re** [comment]
Yup, that is exactly right.

Potentially unsatisfying workarounds, in case someone finds this and doesn't want to dig through #160 for the workarounds:
- supply messages to gpg as files instead of piping them into stdin
- explicitly supply the length of the message by supplying the `--set-filesize ##`  flag on GPG
