### ISSUE TITLE
Armorable.ascii_unarmor fails for cleartext sig.

### ISSUE THREAD

**Issue by J08nY** [SecurityInnovation/PGPy#184]
When loading the following ASCII-armored blob through `Armorable.ascii_unarmor`, the resulting `dict` has the `cleartext` part empty (`None`). With my understanding of `ascii_unarmor` it should contain `"Some signed text."`. This in turn makes `PGPMessage.from_blob()` fail on the following message.
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Some signed text.
-----BEGIN PGP SIGNATURE-----

iMoEAQEIADQWIQTUqUiGscoglqZFjlxH8QwIeIS3WAUCWUrxlhYccnNhLTEwMjRi
QGV4YW1wbGUub3JnAAoJEEfxDAh4hLdYmWAD/2t77jO74yCTsPmjOUfyYGgIuTOX
DYtl9Eg+q6DWC7dPQzaclTXJwWBKG5viezAwxZLzWyswWX73o0Y4HfdQQf0098yr
FrVlFvbAEQwTTv6ojmCqFmRii2boSCQBqeWGETv8XkzVYfevUL/FXdIYdBXvWj3O
nIOef7FIn0COk909
=W+Nq
-----END PGP SIGNATURE-----
```

**Comment by J08nY** [comment]
I created this message with `echo "Some signed text." | gpg --clear-sign`. I noticed that creating with `echo -e "Some signed text.\n" | gpg --clear-sign` makes it work, the cleartext part is parsed in `ascii_unarmor` and the message as a whole is parsed in `PGPMessage`.

**Comment by Commod0re** [comment]
confirmed. Regex fail should be fixed in 33ba06fd623fb7f19d6298f96d1f7c4b70db50e1

**Comment by J08nY** [comment]
Thanks!

**Comment by wgromniak** [comment]
I'm also affected by this issue. I'd be happy to see the next version with the bugfix released as soon as possible. When are you planning to release?

**Comment by Commod0re** [comment]
Once the remaining issues for the [0.4.2 milestone](https://github.com/SecurityInnovation/PGPy/milestone/12) are either closed or moved back to the next milestone. I want to get it out ASAP, with as many of those bugs fixed as possible.

**Comment by wgromniak** [comment]
Ok, thanks. Nevertheless, it would be great if you could release only the part of bugfixes currently completed, if that's possible in your release schedule. I think it's worth it - makes a whole set of functionality (verifying clearsigned messages) usable for me.

Thanks for the great work on this project!

**Comment by Commod0re** [comment]
I'll do my best to get it out as quickly as I can 8)
