### ISSUE TITLE
Cannot decrypt files encrypted with PGPy?

### ISSUE THREAD

**Issue by kevinl95** [SecurityInnovation/PGPy#201]
Hello,

I think there is something I am doing wrong, otherwise it appears that I cannot decrypt files that I encrypted using PGPy. I followed the example for encrypting:

`
                        to_encrypt = pgpy.PGPMessage.new(

                            filename, file=True)

                        ciph = pgpy.constants.SymmetricKeyAlgorithm.AES256

                        session_key = ciph.gen_key()

                        enc_file_data = public_key.encrypt(

                            to_encrypt,

                            cipher=ciph,

                            sessionkey=session_key)

                        del session_key

                        output_file.write(bytes(enc_file_data))

                        output_file.close()`

I have used GPG to produce public and private key files. I open the public key file and use it to encrypt the file here.
If I take the file object and check if it is encrypted, PGPy tells me that it is and I can retrieve the encrypter.

If I then attempt to decrypt this same file:

` 
                       to_decrypt = pgpy.PGPMessage.new(

                            filename, file=True)

                        print(to_decrypt.encrypters)

                        print(to_decrypt.is_encrypted)

                        dec_file_data = private_key.decrypt(to_decrypt)

                        output_file.write(bytes(dec_file_data))

                        output_file.close()`

I open the private key file instead here (private_key) and use it to try to decrypt the file I just encrypted. Those two print statements tell me that the file is not encrypted and there are no encryptors. This is the same file that I have just saved- I have verified this by passing in filename as the path to my encrypted file. Can someone please tell me what I am forgetting to add? Thanks!

**Comment by J08nY** [comment]
Could you test decrypting the output file with gpg? Also you don't open the `output_file` in your code snippet. Could you verify that it was indeed saved correctly?

**Comment by kevinl95** [comment]
Thanks for your response! Decrypting with GPG works flawlessly. I do open the output_file sorry, I forgot the outer while loop:

`with open(out_dir, 'wb') as output_file:
                        print(filename)
                        to_decrypt = pgpy.PGPMessage.new(
                            filename, file=True)
                        print(to_decrypt.encrypters)
                        print(to_decrypt.is_encrypted)
                        dec_file_data = private_key.decrypt(to_decrypt)
                        output_file.write(bytes(dec_file_data))
                        output_file.close()`

**Comment by J08nY** [comment]
Oh I see. `PGPMessage.new` is for creating a message you want to sign/encrypt. To load an encrypted message you either do `PGPMessage.from_blob()` and pass it either an ASCII-Armored blob or binary blob of the message, or you do `PGPMessage.from_file()` and pass it the file path. So you should change:

```python
to_decrypt = pgpy.PGPMessage.from_file(filename)
```

**Comment by kevinl95** [comment]
Thanks! That solved the problem. The file is now recognized as encrypted.
