### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero on Decrypt

### ISSUE THREAD

**Issue by kevinl95** [SecurityInnovation/PGPy#203]
When decrypting a file using PGPy, Cryptography, and Python 3.6.2 the following traceback is received:

```
Traceback (most recent call last):
  File "/Users/test/Documents/FilePrep2/modules/pgp_mod.py", line 274, in process
    dec_file_data = private_key.decrypt(to_decrypt)
  File "/usr/local/lib/python3.6/site-packages/pgpy/pgp.py", line 2230, in decrypt
    return self.subkeys[skid].decrypt(message)
  File "/usr/local/lib/python3.6/site-packages/pgpy/pgp.py", line 2235, in decrypt
    alg, key = pkesk.decrypt_sk(self._key)
  File "/usr/local/lib/python3.6/site-packages/pgpy/packet/packets.py", line 213, in decrypt_sk
    ct = b'\x00' * ((pk.keymaterial.__privkey__().key_size // 8) - len(ct)) + ct
  File "/usr/local/lib/python3.6/site-packages/pgpy/packet/fields.py", line 1113, in __privkey__
    rsa.rsa_crt_iqmp(self.p, self.q),
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 200, in rsa_crt_iqmp
    return _modinv(q, p)
  File "/usr/local/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 193, in _modinv
    return x1 % m
ZeroDivisionError: integer division or modulo by zero
```
This seems to point towards Cryptography being the culprit. A few more details:

- I generate my keys using GPG and exporting a public key file and a private key file which I use for encryption/decryption
- I create PGPy keys from file using these two files

My code looks like this:

```Python
with open(out_dir, 'wb') as output_file:
                        try:
                            to_decrypt = pgpy.PGPMessage.from_file(file_path)
                            print(to_decrypt.is_encrypted)
                            print(to_decrypt.encrypters)
                            dec_file_data = private_key.decrypt(to_decrypt)
                            output_file.write(bytes(dec_file_data))
                            output_file.close()
```

The file is recognized as encrypted. I have tried to reinstall the Cryptography package and I have gone through making sure that I have dependencies installed. Any ideas?

**Comment by kevinl95** [comment]
Oh! The keys are RSA, I just verified this.

**Comment by Commod0re** [comment]
What is the output of `private_key.is_protected`? It looks like you didn't do anything to unlock the private key yet

**Comment by Commod0re** [comment]
Try this, but using the passphrase you chose when generating the key in place of "Super Secret Passphrase":

```python
with private_key.unlock("Super Secret Passphrase") as unlocked:
    dec_file_data = unlocked.decrypt(to_decrypt)
```

**Comment by kevinl95** [comment]
That was absolutely the problem, I keep forgetting steps. Thank you so much for your help, I'm learning how public/private key encryption works as I build out this feature.

**Comment by Commod0re** [comment]
No problem at all. It is at least highlighting where error messages could be more helpful, so thank you for using the library and submitting reports!
