### ISSUE TITLE
SignatureVerification.sigsubj.by is a keyid not PGPKey

### ISSUE THREAD

**Issue by J08nY** [SecurityInnovation/PGPy#214]
The `SignatureVerification` docstrings state that the `sigsubj.by` should be of type, `pgpy.PGPKey`, while in reality what comes out of `key.verify()` has `sigsubj.by` a keyid string.

        """
        A generator yielding namedtuples of all signatures that were successfully verified
        in the operation that returned this instance. The namedtuple has the following attributes:

        ``sigsubj.verified`` - ``bool`` of whether the signature verified successfully or not.

        ``sigsubj.by`` - the :py:obj:`~pgpy.PGPKey` that was used in this verify operation.

        ``sigsubj.signature`` - the :py:obj:`~pgpy.PGPSignature` that was verified.

        ``sigsubj.subject`` - the subject that was verified using the signature.
        """

**Comment by Commod0re** [comment]
fixed in #215
