### ISSUE TITLE
Armorable should not automatically insert PGPy version information

### ISSUE THREAD

**Issue by dkg** [SecurityInnovation/PGPy#228]
GnuPG [no longer publishes the version information by default](https://lists.gnupg.org/pipermail/gnupg-devel/2016-August/031424.html).  For a good summary of why this inclusion of metadata might not be a great idea, see [this post by ilf](https://lists.gnupg.org/pipermail/gnupg-devel/2016-August/031467.html).

It'd be great if PGPy's Armorable class didn't default its `ascii_headers` to a dictionary containing the same sort of metadata.

**Comment by Commod0re** [comment]
Makes perfect sense.  Removed the default version header.
