### ISSUE TITLE
pythonista support on ios

### ISSUE THREAD

**Issue by eddo888** [SecurityInnovation/PGPy#230]
it would be awesome if this worked on pythonista for ios, it installs ok with ‘’’pip install PGPy’’’ using StaSh
but misses the cryptographics.hazmat library

https://github.com/ywangd/stash
http://omz-software.com/pythonista/

**Comment by Commod0re** [comment]
Unless `pip install cryptography` fixes it, there's probably not much I can do about this, unfortunately. Better report it to the [cryptography](https://github.com/pyca/cryptography) maintainers, and/or the Pythonista developers to see if anytthing can be done.
