### ISSUE TITLE
Decrypt pgp data chunk by chunk

### ISSUE THREAD

**Issue by xuyuanme** [SecurityInnovation/PGPy#233]
Will there be an option to decrypt pgp data chunk by chunk?

The use case is, we have a service receiving large pgp file, chunk by chunk. Instead of landing the whole file to local disk (or memory), we want to decrypt the chunks on the fly and pass to 3rd party service.

We're looking for feature similar to how zlib library is decompressing gzip file:

```python
import zlib
decompressobj = zlib.decompressobj(32 + zlib.MAX_WBITS)
return decompressobj.decompress(data_chunk)
```

'decompressobj' consumes the incoming bytes, if the bytes are less than a zipped chunk, it'll return empty string and keep consuming the next piece of bytes.

So can pgp process the encrypted file in similar way?

**Comment by Commod0re** [comment]
That is essentially how I intend #216 to work, yes. It's not implemented yet, but I am working on it.

**Comment by Commod0re** [comment]
closing as a duplicate issue 8)
