### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by dkg** [SecurityInnovation/PGPy#236]
there have been a number of bugfixes accumulating in the master branch, but we haven't had a release since 0.4.3.  I've just cleaned up and improved the debian packaging so i think it will move to testing in a few days -- and it's shipping a copy of local docs as well, which is better-formatted than what i had been shipping.

@Commod0re , i wrote you an e-mail about this, but i think the e-mail address i have for you is bouncing with a "Disabled User" message.  If you want to contact me privately with a better e-mail address to use, i'd appreciate it.

**Comment by evilaliv3** [comment]
@dkg: do you have any update for this? now that the library is packaged for debian we are evaluating its usage in GlobaLeaks as well as replacement for python-gnupg :(

thanks!

**Comment by anarcat** [comment]
It certainly looks like @Commod0re doesn't have the time to respond to issues here unfortunately. I would recommend that whoever wants to work on or with PGPy consider creating an official for and start merging the many excellent PRs that are pending in the queue.

This project has a lot of potential, it just needs someone to followup with it. I wish I had time to do so, but I'm afraid my own hands are full...

**Comment by Commod0re** [comment]
v0.5.0 and v0.5.1 were released today! Thanks for your patience with my tight schedule everyone!
