### ISSUE TITLE
PGPKey.pubkey() should return self if this is a public key

### ISSUE THREAD

**Issue by dkg** [SecurityInnovation/PGPy#255]
it's not clear why `PGPKey.pubkey()` returns `None` if `self` is already a public key.  If it is a public key, why not just return itself?

**Comment by Commod0re** [comment]
I just didn't think of it, but it's a good idea

**Comment by dkg** [comment]
is there any ownership issue with just returning self?  what happens if someone is used to doing `key.pubkey` and then modifying the returned object, will those changes effect the original object if `key` happens to be a public key?

On a privkey, the returned thing is a new object, right.  i confess i don't understand the python memory ownership model well enough to know whether sometimes returning a newly-allocated object and other times returning an already-allocated thing.

**Comment by Commod0re** [comment]
Python is pass-by-object-reference, so `return self` returns a reference to the same object and that will work as expected

In the case of returning the pubkey from a privkey object, it has to build the pubkey first like you said, _unless_ it already has a reference to an existing pubkey object, in which case it will return that reference instead
