### ISSUE TITLE
please drop the "debian" branch, and rename it to "debian/master"

### ISSUE THREAD

**Issue by dkg** [SecurityInnovation/PGPy#274]
[DEP-14](https://dep-team.pages.debian.net/deps/dep14/) recommends debian packaging to have dedicated branch naming within a `debian/` namespace.

Over on https://github.com/dkg/PGPy i've got a `debian/master` branch that shows the packaging cleanup i've done for 0.5.2-1, which i've just uploaded to debian unstable.  It would be great if you could drop the `debian` branch here (git tends to complain if a branch name is a strict prefix of a another slash-separated branch name), and import my `debian/master` branch into this main repo.

thanks for the 0.5.2 release, this is an exciting day for PGPy!

**Comment by Commod0re** [comment]
debian branch has been dropped!
