### ISSUE TITLE
unarmoring is brittle

### ISSUE THREAD

**Issue by dkg** [SecurityInnovation/PGPy#276]
PGPy appears to be very good at generating standards-compliant ASCII-armored messages.

However, it is pretty brittle at reading subtly-non-standards-compliant messages.

In [some examples](https://gist.github.com/Valodim/59ae7c8a54abd7746412ae114c333721) there is a lacking checksum, or the lines of base64 are more than 76 characters long.

It might make sense to relax the constraints on import a little bit to deal with this kind of sloppiness.  In particular:

 * if no checksum is present, ignore its absence (it's not clear that the checksum provides much help on modern transmissions and networks)
 * limit the base64 lines to some larger but not outrageous limit (e.g. 1024 characters)

PGPy should continue to emit well-formed ASCII armor, of course!

**Comment by dkg** [comment]
hm, `Armorable.__armor_regex` actually seems to limit it to 75 characters (`{1,75}`), which i think is even stricter than the spec.

**Comment by Commod0re** [comment]
ascii_unarmor adheres to the [RFC4880 spec's description of Radix-64 encoding](https://tools.ietf.org/html/rfc4880#section-6.3):

> The encoded output stream must be represented in lines of no more than 76 characters each.

(this includes the newline character)


But, more importantly, this is outside the scope of problems PGPy is trying to solve. We are not an input massaging library, or a user application, we're an OpenPGP library, and so we should remain comfortable balking at input that is not compliant, leaving any given application to decide whether or not to accept input that is not 100% to-spec, and massage that into something we accept, or not.
