### ISSUE TITLE
How to decrypt a PGP file using Public Key

### ISSUE THREAD

**Issue by felixcheruiyot** [SecurityInnovation/PGPy#288]
I have an issue, also highlighted here > https://stackoverflow.com/questions/57807242/how-to-decrypt-a-pgp-file-using-public-key-in-pgpy

I have a Public shared to me and I'm loading it as shown below:

    key_path = os.environ.get('ESB_FILES_PUBLIC_KEY')
    key, _ = pgpy.PGPKey.from_file(key_path)

I try to decrypt the file using this key

    message_from_file = pgpy.PGPMessage.from_file(filepath)
    raw_message = key.decrypt(message_from_file).message
    print(raw_message)

It doesn't work and I get this error instead `pgpy.errors.PGPError: Expected: is_public == False. Got: True`

Any idea on how to decrypt an PGP file in Python with only the Public Key.

Thanks

**Comment by Commod0re** [comment]
You can't; public keys can only be used for encryption and signature verification. Decryption and signing require the private key.

**Comment by felixcheruiyot** [comment]
Thanks @Commod0re for the quick reply.

Is this how PGP generally works or basically based on the scope of the PGPy module?

Please advise.

Thanks.

**Comment by Commod0re** [comment]
Yes, this is generally how public-key cryptography works

**Comment by felixcheruiyot** [comment]
Thanks @Commod0re

**Comment by sydneywu** [comment]
Sorry to bring out an old issue. From my understanding of PGP, it requires 2 sets of key for encrypting and 2 sets of key for decrypting. So for example, when a sender encrypt a file for me:

Sender will need to use his private key and my public key to encrypt.
I will need to use my private key and sender's public key to decrypt.

You can see in this guide: https://www.howtogeek.com/427982/how-to-encrypt-and-decrypt-files-with-gpg-on-linux/
"To send a file securely, you encrypt it with your private key and the recipient’s public key. To decrypt the file, they need their private key and your public key."
