### ISSUE TITLE
new release please?

### ISSUE THREAD

**Issue by dkg** [SecurityInnovation/PGPy#314]
Hi @Commod0re  -- it's been months since some significant cleanup has been done on PGPy, and it would be really nice to get out a new release, even if it's just a stopgap release before we get rid of python2 (#300).

**Comment by Commod0re** [comment]
I'll make some time to publish a new release soon

**Comment by dkg** [comment]
ping on this.  it's really overdue ☺

**Comment by TensorTom** [comment]
+1

**Comment by dkg** [comment]
It's been almost 6 months now since i first asked -- and that itself was several months after it would have been good to have a release.

In the absence of activity upstream, i've cloned this repo to https://github.com/dkg/PGPy2 and will be start work on making something releasable under the new name "PGPy2"

I'd be happy to drop that work if PGPy shows some signs of life!

**Comment by J-M0** [comment]
How about we do one more release called 0.5.3 and say it's the last one to support Python 2.7 and 3.4. After that we can work on 0.6, drop those versions, and start cleaning up and modernizing the code.

**Comment by J-M0** [comment]
0.5.3 has been released with bugfixes along with a bunch of cleanup to improve the docs and modernize the packaging process.

I'll make some changes tomorrow to start work on 0.6 and set the groundwork for the big cleanup.
