### ISSUE TITLE
deprecate SHA-1

### ISSUE THREAD

**Issue by dkg** [SecurityInnovation/PGPy#316]
Relying on the collision resistance of SHA-1 has been dubious for years.  The writing has been on the wall since [Wang et al in 2005](https://dx.doi.org/10.1007/11535218_2),  but an actual collision is within reach of a moderately-funded attacker as of [this past year](https://shattered.io/).

pgpy should treat signatures made using SHA-1 the same as it treats signatures made using MD5.

**Comment by teythoon** [comment]
Relevant test: https://tests.sequoia-pgp.org/#Signature_over_the_shattered_collision
