### ISSUE TITLE
PGPy compatibility break with Python < 3.8

### ISSUE THREAD

**Issue by MarcinGinszt** [SecurityInnovation/PGPy#368]
https://github.com/SecurityInnovation/PGPy/commit/6e34a00a50ff9e1eeefa0cfdeca23cb0f274af0b
This commit uses the `logging.debug` function with keyword argument `stacklevel`. 
`stacklevel` in this library is allowed as a keyword argument for Python versions >= 3.8
https://docs.python.org/3/library/logging.html?highlight=stacklevel
`Changed in version 3.8: The stacklevel parameter was added.`
Running this code on Python 3.6 results in an error
```
  | File "/opt/app-root/lib/python3.6/site-packages/pgpy/decorators.py", line 104, in usage
  | "".format(**em), stacklevel=4)
  | File "/usr/lib64/python3.6/logging/__init__.py", line 1912, in debug
  | root.debug(msg, *args, **kwargs)
  | File "/usr/lib64/python3.6/logging/__init__.py", line 1296, in debug
  | self._log(DEBUG, msg, args, **kwargs)
  | TypeError: _log() got an unexpected keyword argument 'stacklevel'
```

**Comment by J-M0** [comment]
Hey @MarcinGinszt, thanks for the report! Would you mind sharing some example code that triggers this? I'd like to make a test.

**Comment by MarcinGinszt** [comment]
```
key = PGPKey.from_blob(key_blob)[0]
encrypted = key.encrypt(msg)
```

**Comment by MarcinGinszt** [comment]
Any code using `PGPKey.encrypt()` will fail. Thanks!

**Comment by J-M0** [comment]
Can you provide a more detailed sample please? I know the parameter isn't in older Python versions, but I'm having trouble triggering the bug.

**Comment by J-M0** [comment]
Nevermind, I got it
