### ISSUE TITLE
spurious file `pgpy/pgp1.py` ?

### ISSUE THREAD

**Issue by dkg** [SecurityInnovation/PGPy#419]
b8c28c5a4620ba3df20ffac4cc7cadbff0691645 appears to have introduced a file `pgpy/pgp1.py`, which is very similar to `pgpy/pgp.py` but slightly different.  it is also not used anywhere.  i suspect this is just a mistake.

**Comment by dkg** [comment]
I think this can be resolved with #416

**Comment by Commod0re** [comment]
#423
