### ISSUE TITLE
Acceptance of armored PGP messages without a checksum 

### ISSUE THREAD

**Issue by lubux** [SecurityInnovation/PGPy#453]
Hey 👋  PGPy currently does not accept armored PGP messages without a checksum, see:
[OpenPGP interoperability test suite](https://tests.sequoia-pgp.org/#Encrypt-Decrypt_roundtrip_with_key__Bob_)

The checksum is optional according to [RFC 4880](https://datatracker.ietf.org/doc/html/rfc4880#section-6) and is now discouraged by the [crypto-refresh](https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-10.html#name-forming-ascii-armor).
This may lead to compatibility issues in the future.

**Comment by dkg** [comment]
This is resolved in #451, along with several other changes.  see 2651a134cd301fcd709f1d845c22b83373dec147
